import {
  BarChart3,
  CalendarClock,
  Code2,
  FileText,
  Gauge,
  Layers,
  LayoutTemplate,
  LifeBuoy,
  LineChart,
  Mail,
  Megaphone,
  MapPin,
  Palette,
  PenTool,
  RefreshCw,
  Rocket,
  Search,
  ShieldCheck,
  Smartphone,
  Target,
  TrendingUp,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { ServiceIconKey } from "@/lib/types";

export const serviceIcons: Record<string, LucideIcon> = {
  webb: Code2,
  seo: Search,
  design: Palette,
  tillvaxt: TrendingUp,
  automation: Zap,
  support: LifeBuoy,
};

// Icons used inside a service's features/process cards — a separate,
// broader set from serviceIcons above (which only labels the six top-level
// services themselves).
export const serviceFeatureIcons: Record<ServiceIconKey, LucideIcon> = {
  search: Search,
  gauge: Gauge,
  "file-text": FileText,
  "map-pin": MapPin,
  "line-chart": LineChart,
  target: Target,
  "code-2": Code2,
  smartphone: Smartphone,
  "layout-template": LayoutTemplate,
  "palette-icon": Palette,
  layers: Layers,
  "pen-tool": PenTool,
  "trending-up": TrendingUp,
  megaphone: Megaphone,
  "bar-chart": BarChart3,
  zap: Zap,
  workflow: Workflow,
  mail: Mail,
  "calendar-clock": CalendarClock,
  "life-buoy": LifeBuoy,
  "shield-check": ShieldCheck,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
};
